// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String realtimeDatabaseUrl =
      "https://metroswap-73a05-default-rtdb.firebaseio.com";

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOwAVlWP4n5o2WFa2yYgsbkVADspyMr2g',
    appId: '1:614391071848:web:e13a946ba6dd85c6cce7dd',
    messagingSenderId: '614391071848',
    projectId: 'metroswap-73a05',
    authDomain: 'metroswap-73a05.firebaseapp.com',
    storageBucket: 'metroswap-73a05.firebasestorage.app',
    measurementId: 'G-W1M8JRDM9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFR1QNpaLEUSScEfOPa2YIQNMpYIEw2vY',
    appId: '1:614391071848:android:8e52650293ec4003cce7dd',
    messagingSenderId: '614391071848',
    projectId: 'metroswap-73a05',
    storageBucket: 'metroswap-73a05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5wi_wuR1q4bUk1sHSs2w8ECJIluWdf9s',
    appId: '1:614391071848:ios:5ed2ecc72888b575cce7dd',
    messagingSenderId: '614391071848',
    projectId: 'metroswap-73a05',
    storageBucket: 'metroswap-73a05.firebasestorage.app',
    iosClientId: '614391071848-79cmp9ik5qn4vdifidg2b37jhj9ql4pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.metroswap',
  );
}
